This is makeindex, version 2.16 [MiKTeX 23.10.12].
Scanning style file ./thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (11 entries accepted, 0 rejected).
Sorting entries....done (45 comparisons).
Generating output file thesis.acr....done (17 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
